TRUNCATE table Permission AND COMMIT NO CHECK;
TRUNCATE table Event AND COMMIT NO CHECK;
TRUNCATE table VoteCategory AND COMMIT NO CHECK;
TRUNCATE table VoteCategoryType AND COMMIT NO CHECK;
TRUNCATE table VoteOption AND COMMIT NO CHECK;
TRUNCATE table User_Event AND COMMIT NO CHECK;
TRUNCATE table Vote AND COMMIT NO CHECK;
TRUNCATE table UserAccount AND COMMIT NO CHECK;