CREATE TABLE IF NOT EXISTS UserAccount 
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
username varchar(256) NOT NULL,
password varchar(256),
displayName varchar(64),
email varchar(128) NOT NULL,
accountType varchar(64) NOT NULL,
PRIMARY KEY (Id),
CONSTRAINT uc_Email UNIQUE(email)
);
 
CREATE TABLE IF NOT EXISTS Permission
(
userId int NOT NULL,
permissionName varchar(25) NOT NULL,
CONSTRAINT uc_Permission UNIQUE (userId,permissionName),
FOREIGN KEY (userId) REFERENCES UserAccount(Id)
);


CREATE TABLE IF NOT EXISTS Event
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
name varchar(50) NOT NULL,
startTime timestamp,
endTime timestamp,
description varchar(255) NOT NULL,
eventType varChar(64) NOT NULL,
version int  DEFAULT 0 NOT NULL,
PRIMARY KEY (Id)

);

Create TABLE IF NOT EXISTS User_Event
(
userId int not NULL,
eventId int not NULL,
CONSTRAINT uc_User_Event UNIQUE (userId,eventId),
FOREIGN KEY (userId) REFERENCES UserAccount(Id),
FOREIGN KEY (eventId) REFERENCES Event(Id)
);

Create TABLE IF NOT EXISTS Admin_Event
(
userId int not NULL,
eventId int not NULL,
CONSTRAINT uc_Admin_Event UNIQUE (userId,eventId),
FOREIGN KEY (userId) REFERENCES UserAccount(Id),
FOREIGN KEY (eventId) REFERENCES Event(Id)
);

CREATE TABLE IF NOT EXISTS VoteCategory
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
eventId int NOT NULL,
categoryName varchar(50) NOT NULL,
description varchar(255) NOT NULL,
version int  DEFAULT 0 NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (eventId) REFERENCES Event(Id)
);


Create TABLE IF NOT EXISTS VoteOption
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
voteCategoryId int,
optionName varchar(50) NOT NULL,
version int  DEFAULT 0 NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (voteCategoryId) REFERENCES VoteCategory(Id)
);

Create TABLE IF NOT EXISTS Vote
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
userId int NOT NULL,
voteOptionId int NOT NULL,
voteCategoryId int NOT NULL,
version int  DEFAULT 0 NOT NULL,
voteTime timestamp NOT NULL,
PRIMARY KEY (Id),
CONSTRAINT uc_Vote UNIQUE (userId,voteCategoryId),
FOREIGN KEY (voteOptionId) REFERENCES VoteOption(Id),
FOREIGN KEY (userId) REFERENCES UserAccount(Id)
);
