drop table UserAccount if exists;
 
CREATE TABLE UserAccount
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
username varchar(50) NOT NULL,
password varchar(25),
displayName varchar(30),
accountType varchar(50) NOT NULL,
PRIMARY KEY (Id)
);

CREATE TABLE Permission
(
userId int NOT NULL,
permissionName varchar(25) NOT NULL,
CONSTRAINT uc_Permission UNIQUE (userId,permissionName),
FOREIGN KEY (userId) REFERENCES UserAccount(Id)
)


CREATE TABLE Event
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
adminId int NOT NULL,
name varchar(50) NOT NULL,
description varchar(255) NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (adminId) REFERENCES UserAccount(Id)
);

Create TABLE User_Event
(
userId int not NULL,
eventId int not NULL,
CONSTRAINT uc_User_Event UNIQUE (userId,eventId),
FOREIGN KEY (userId) REFERENCES UserAccount(Id),
FOREIGN KEY (eventId) REFERENCES Event(Id)
)

CREATE TABLE VoteCategory
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
eventId int NOT NULL,
categoryName varchar(50) NOT NULL,
description varchar(255) NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (eventId) REFERENCES Event(Id)
)

CREATE TABLE VoteCategoryType
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
voteCategoryId int NOT NULL,
voteCategoryType varchar(50) NOT NULL,
PRIMARY KEY (Id),
CONSTRAINT uc_VoteOptionType UNIQUE (voteCategoryId,voteCategoryType),
FOREIGN KEY (voteCategoryId) REFERENCES VoteCategory(Id)
)

CREATE TABLE VoteSubCategory
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
voteCategoryId int NOT NULL,
subCategoryName varchar(50) NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (voteCategoryId) REFERENCES VoteCategory(Id)
)

Create TABLE VoteOption
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
voteCategoryId int,
voteSubCategoryId int, 
optionName varchar(50) NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (voteCategoryId) REFERENCES VoteCategory(Id),
FOREIGN KEY (voteSubCategoryId) REFERENCES VoteSubCategory(Id)
)

Create TABLE Vote
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
userId int NOT NULL,
voteOptionId int NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (voteOptionId) REFERENCES VoteOption(Id)
)
