drop table Persons if exists;
 
CREATE TABLE Persons
(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
LastName varchar(255),
FirstName varchar(255),
Address varchar(255),
City varchar(255),
Email varchar(255)
);