package edu.columbia.ase.auctionhouse.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-09T22:17:34.217-04:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://webservice.auctionhouse.ase.columbia.edu/", name = "AuctionHouseWebServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface AuctionHouseWebServiceImpl {

    @WebResult(name = "customerId", targetNamespace = "")
    @Action(input = "http://webservice.auctionhouse.ase.columbia.edu/AuctionHouseWebServiceImpl/registerCustomerRequest", output = "http://webservice.auctionhouse.ase.columbia.edu/AuctionHouseWebServiceImpl/registerCustomerResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://webservice.auctionhouse.ase.columbia.edu/AuctionHouseWebServiceImpl/registerCustomer/Fault/Exception")})
    @RequestWrapper(localName = "registerCustomer", targetNamespace = "http://webservice.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.webservice.RegisterCustomer")
    @WebMethod
    @ResponseWrapper(localName = "registerCustomerResponse", targetNamespace = "http://webservice.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.webservice.RegisterCustomerResponse")
    public java.lang.Integer registerCustomer(
        @WebParam(name = "customerWsdlUrl", targetNamespace = "")
        java.lang.String customerWsdlUrl
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://webservice.auctionhouse.ase.columbia.edu/AuctionHouseWebServiceImpl/getActiveAuctionsRequest", output = "http://webservice.auctionhouse.ase.columbia.edu/AuctionHouseWebServiceImpl/getActiveAuctionsResponse")
    @RequestWrapper(localName = "getActiveAuctions", targetNamespace = "http://webservice.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.webservice.GetActiveAuctions")
    @WebMethod
    @ResponseWrapper(localName = "getActiveAuctionsResponse", targetNamespace = "http://webservice.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.webservice.GetActiveAuctionsResponse")
    public java.util.List<edu.columbia.ase.auctionhouse.webservice.Auction> getActiveAuctions();

    @Action(input = "http://webservice.auctionhouse.ase.columbia.edu/AuctionHouseWebServiceImpl/placeBidRequest", output = "http://webservice.auctionhouse.ase.columbia.edu/AuctionHouseWebServiceImpl/placeBidResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://webservice.auctionhouse.ase.columbia.edu/AuctionHouseWebServiceImpl/placeBid/Fault/Exception")})
    @RequestWrapper(localName = "placeBid", targetNamespace = "http://webservice.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.webservice.PlaceBid")
    @WebMethod
    @ResponseWrapper(localName = "placeBidResponse", targetNamespace = "http://webservice.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.webservice.PlaceBidResponse")
    public void placeBid(
        @WebParam(name = "customerId", targetNamespace = "")
        int customerId,
        @WebParam(name = "auctionId", targetNamespace = "")
        int auctionId,
        @WebParam(name = "bidAmount", targetNamespace = "")
        double bidAmount
    ) throws Exception_Exception;
}
