
package edu.columbia.ase.auctionhouse.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-09T22:17:34.193-04:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "Exception", targetNamespace = "http://webservice.auctionhouse.ase.columbia.edu/")
public class Exception_Exception extends java.lang.Exception {
    
    private edu.columbia.ase.auctionhouse.webservice.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, edu.columbia.ase.auctionhouse.webservice.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, edu.columbia.ase.auctionhouse.webservice.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public edu.columbia.ase.auctionhouse.webservice.Exception getFaultInfo() {
        return this.exception;
    }
}
