package edu.columbia.ase.auctionhouse.customer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-10T17:26:21.011-04:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "AuctionHouseCustomer", 
                  wsdlLocation = "http://localhost:7777/AuctionHouseCustomer?wsdl",
                  targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/") 
public class AuctionHouseCustomer extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://customer.auctionhouse.ase.columbia.edu/", "AuctionHouseCustomer");
    public final static QName WebServiceCustomerPort = new QName("http://customer.auctionhouse.ase.columbia.edu/", "WebServiceCustomerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7777/AuctionHouseCustomer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuctionHouseCustomer.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7777/AuctionHouseCustomer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuctionHouseCustomer(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuctionHouseCustomer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuctionHouseCustomer() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuctionHouseCustomer(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuctionHouseCustomer(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AuctionHouseCustomer(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WebServiceCustomer
     */
    @WebEndpoint(name = "WebServiceCustomerPort")
    public WebServiceCustomer getWebServiceCustomerPort() {
        return super.getPort(WebServiceCustomerPort, WebServiceCustomer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceCustomer
     */
    @WebEndpoint(name = "WebServiceCustomerPort")
    public WebServiceCustomer getWebServiceCustomerPort(WebServiceFeature... features) {
        return super.getPort(WebServiceCustomerPort, WebServiceCustomer.class, features);
    }

}
