package edu.columbia.ase.auctionhouse.customer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-10T17:26:20.978-04:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", name = "WebServiceCustomer")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceCustomer {

    @Action(input = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/auctionWonRequest", output = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/auctionWonResponse")
    @RequestWrapper(localName = "auctionWon", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.AuctionWon")
    @WebMethod
    @ResponseWrapper(localName = "auctionWonResponse", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.AuctionWonResponse")
    public void auctionWon(
        @WebParam(name = "auctionId", targetNamespace = "")
        int auctionId,
        @WebParam(name = "auctionPrice", targetNamespace = "")
        double auctionPrice
    );

    @Action(input = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/setAuctionHouseWebServiceURLRequest", output = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/setAuctionHouseWebServiceURLResponse")
    @RequestWrapper(localName = "setAuctionHouseWebServiceURL", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.SetAuctionHouseWebServiceURL")
    @WebMethod
    @ResponseWrapper(localName = "setAuctionHouseWebServiceURLResponse", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.SetAuctionHouseWebServiceURLResponse")
    public void setAuctionHouseWebServiceURL(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @Action(input = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/setCustomerURLRequest", output = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/setCustomerURLResponse")
    @RequestWrapper(localName = "setCustomerURL", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.SetCustomerURL")
    @WebMethod
    @ResponseWrapper(localName = "setCustomerURLResponse", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.SetCustomerURLResponse")
    public void setCustomerURL(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @Action(input = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/setIdRequest", output = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/setIdResponse")
    @RequestWrapper(localName = "setId", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.SetId")
    @WebMethod
    @ResponseWrapper(localName = "setIdResponse", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.SetIdResponse")
    public void setId(
        @WebParam(name = "customerId", targetNamespace = "")
        int customerId
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/getCustomerURLRequest", output = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/getCustomerURLResponse")
    @RequestWrapper(localName = "getCustomerURL", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.GetCustomerURL")
    @WebMethod
    @ResponseWrapper(localName = "getCustomerURLResponse", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.GetCustomerURLResponse")
    public java.lang.String getCustomerURL();

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/getAuctionHouseWebServiceURLRequest", output = "http://customer.auctionhouse.ase.columbia.edu/WebServiceCustomer/getAuctionHouseWebServiceURLResponse")
    @RequestWrapper(localName = "getAuctionHouseWebServiceURL", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.GetAuctionHouseWebServiceURL")
    @WebMethod
    @ResponseWrapper(localName = "getAuctionHouseWebServiceURLResponse", targetNamespace = "http://customer.auctionhouse.ase.columbia.edu/", className = "edu.columbia.ase.auctionhouse.customer.GetAuctionHouseWebServiceURLResponse")
    public java.lang.String getAuctionHouseWebServiceURL();
}
